#version : '3,7'
#services:
#  db:
#    image: postgres
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 1234
#      POSTGRES_DB: node_postgres
#    volumes:
#      - ./pgdata:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    web:
#      image: manik-api
#      depends_on:
#        - db
#      ports:
#        - "4000:4000"


version: '3.9'

services:
  server:
    build: .
    ports:
      - '5000:5000'
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '1234'
      POSTGRES_USER: 'docker'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: